---
# - name: Install Postgresql to CentOS
  # block:
  #   - name: "Install packages"
  #     dnf: "name={{ item }} state=present"
  #     with_items:
  #       - postgresql
  #       - postgresql-server

  #   - name: "Install Python packages"
  #     pip: "name={{ item }}  state=present"
  #     with_items:
  #       - psycopg2-binary

  #   - name: "Find out if PostgreSQL is initialized"
  #     ansible.builtin.stat:
  #       path: "/var/lib/pgsql/data/pg_hba.conf"
  #     register: postgres_data

  #   - name: "Initialize PostgreSQL"
  #     shell: "postgresql-setup initdb"
  #     when: not postgres_data.stat.exists

  #   - name: "Start and enable services"
  #     service: 
  #       name: postgresql 
  #       state: started 
  #       enabled: yes
  #     notify: restart postgres

  #     handlers:
  #     - name: restart postgres
  #       service: name=postgresql state=restarted
  # when: ansible_facts['distribution'] == 'CentOS'

- name: Install Postgresql to Ubuntu
  block:
    - name: Ensure bash, OpenSSl, and libssl are the latest versions
      apt: name={{ item }} update_cache=true state=present
      with_items:
        - bash
        - openssl
        - libssl-dev
        - libssl-doc
      tags: packages

    - name: Install PostgreSQL
      apt: name={{ item }} update_cache=true state=present
      with_items:
        - postgresql
        - postgresql-contrib
        - libpq-dev

    - name: Ensure the PostgreSQL service is running
      service: name=postgresql state=started enabled=yes
  when: ansible_facts['distribution'] == 'Ubuntu'
    