web:
  hosts:
    server:
  vars:
    ansible_host: 18.194.236.221
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/Workspace/Private-Project/nvrbckdown.cer # if you have
    # ansible_password: PASSWORD # if you use pem key comment password! 