web:
  hosts:
    server:
      ansible_host: 159.65.118.44
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa # if you have
      # ansible_password: waiXeH3esoh9eech  # if you use pem key comment password!