web:
  hosts:
    server:
  vars:
    ansible_host: IP ADDRESS
    ansible_user: USER
    ansible_ssh_private_key_file: PATH # if you have
    ansible_password: PASSWORD # if you use pem key comment password! 