web:
  hosts:
    server:
      ansible_host: 82.148.5.98
      ansible_user: root
      ansible_ssh_private_key_file: ~/Workspace/Kubernetes/SharqTV/sharqtv.pem # if you have
      # ansible_password: waiXeH3esoh9eech  # if you use pem key comment password!