web:
  hosts:
    server:
  vars:
    ansible_host: 
    ansible_ssh_user: 
    ansible_port: 22
    ansible_ssh_private_key_file: # if you have
    ansible_password: # if you use pem key comment password!  