---
- name: Create PG Database and User
  hosts: web
  become: yes
  vars_files: vars.yaml

  tasks:
  - name: "Create {{ db_name }} database"
    postgresql_db:
      state: present
      name: "{{ db_name }}"
    # become: yes
    become_user: postgres

  - name: "Create {{ db_name }} {{ db_user }} with {{ db_password }}"
    postgresql_user:
      state: present
      name: "{{ db_user }}"
      password: "{{ db_password }}"
    # become: yes
    become_user: postgres

  - name: "Grant db {{ db_user }} access to {{ db_name }} db"
    postgresql_privs:
      type: database
      database: "{{ db_name }}"
      roles: "{{ db_user }}"
      privs: ALL
    # become: yes
    become_user: postgres

  # - name: "Allow md5 connection for the db user"
  #   postgresql_pg_hba:
  #     dest: "~/data/pg_hba.conf"
  #     contype: host
  #     databases: all
  #     method: md5
  #     users: "{{ db_user }}"
  #     create: true
  #   become: yes
  #   become_user: postgres
      
    