---
- name: Create PG Database and User
  hosts: web
  become: yes
  vars_files: vars.yaml

  tasks:
  - name: "Create app database"
    postgresql_db:
      state: present
      name: "{{ db_name }}"
    # become: yes
    become_user: postgres

  - name: "Create db user"
    postgresql_user:
      state: present
      name: "{{ db_user }}"
      password: "{{ db_password }}"
    # become: yes
    become_user: postgres

  - name: "Grant db user access to app db"
    postgresql_privs:
      type: database
      database: "{{ db_name }}"
      roles: "{{ db_user }}"
      privs: ALL
    # become: yes
    become_user: postgres

      
    