web:
  hosts:
    server:
      ansible_host: IP
      ansible_user: USERNAME
      ansible_ssh_private_key_file: PEM-KEY_PATH # if you have
      ansible_password: PASSWORD # if you use pem key comment password!
