web:
  hosts:
    server:
  vars:
    ansible_host: 3.18.7.10
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/Workspace/Kubernetes/SharqTV/sharqtv.pem # if you have
    # ansible_password: ezD3d7BHLvQV3Bqt