web:
  hosts:
    main-server: 
      ansible_host: 207.154.254.227
      ansible_user: ansible
      ansible_ssh_private_key_file:  ~/Workspace/Ansible/Practice/ansible-test.pem # if you have
      ansible_password:
      ansible_port: 2221
      
