---
- name: "Templating CI"
  hosts: localhost
  connection: local
  vars_files: vars/vars.yaml

  tasks:
  - name: .gitlab-ci.yaml file
    template: 
      src: "./templates/swarm/.gitlab-swarm.yaml.j2" 
      dest: "{{ service_folder }}/.gitlab-ci.yaml"

  - name: dockerfile file
    copy: 
      src: "./templates/swarm/Dockerfile-node" 
      dest: "{{ service_folder }}/Dockerfile"
  
  - name: Makefile copy
    copy: 
      src: "./templates/Makefile" 
      dest: "{{ service_folder }}/Makefile"

  - name: .build_info file
    template: 
      src: "./templates/.build_info.j2" 
      dest: "{{ service_folder }}/.build_info"