# workspace (GOPATH) configured at /go
FROM golang:1.15 as builder

#
RUN mkdir -p $GOPATH/src/gitlab.udevs.io/{{ PROJECT_NAME }}/{{ SERVICE_NAME }}
WORKDIR $GOPATH/src/gitlab.udevs.io/{{ PROJECT_NAME }}/{{ SERVICE_NAME }}

# Copy the local package files to the container's workspace.
COPY . ./

# installing depends and build
RUN export CGO_ENABLED=0 && \
    export GOOS=linux && \
    make build && \
    mv ./bin/{{ SERVICE_NAME }} /

FROM alpine
COPY --from=builder {{ SERVICE_NAME }} .

ENTRYPOINT ["/{{ SERVICE_NAME }}"]