nginx: nginx # by default latest, for version use nginx=1.18*
user: sharqtv
password: user_password
ssh_key_filename: ssh_file_name
pemfile_path: path_on_your_machine

db_user: db_user_name
db_password: db_user_password
db_name: db_name