nginx: nginx # by default latest, for version use nginx=1.18*
user: sharqtv
password: jeiquof9Aingahsu
ssh_key_filename: sharqtv
pemfile_path: ~/Workspace/Kubernetes/SharqTV

db_user: db_user_name
db_password: db_user_password
db_name: db_name

user_check: false
ssh_key_check: false
nginx_check: false
es_commands_check: false
docker_check: false
postgresql_check: false

# Service is not ready
mongo_check: false